### ISSUE TITLE
Facade\Ignition\Exceptions\ViewException View [layout] not found

### ISSUE THREAD

**Issue by nomadtechiemike** [eduardoarandah/backpacklogviewer#3]
\www\backpack2\resources\views\vendor\log-viewer\backpack\_master.blade.php) 
![error not found](https://user-images.githubusercontent.com/29424378/72339998-e41bb880-36f9-11ea-87b9-9147acc25ad1.jpg)

**Comment by eduardoarandah** [comment]
man, I can't guess! 😂

can you elaborate?

**Comment by nomadtechiemike** [comment]
It will not load as it cannot find the blade file, even though the blade file is in the correct folder

**Comment by pxpm** [comment]
It should be `\www\backpack2\resources\views\vendor\log-viewer\backpack\_master.blade.php` 

It's missing a "\" slash. 

Also make sure you are not running Backpack v4.0 with this package. 

Best,
Pedro

**Comment by TheROPFather** [comment]
`Also make sure you are not running Backpack v4.0 with this package.`

Is there any plan to add support for Backpack 4.0?

I also have this issue.

`
    ErrorException thrown with message "View [layout] not found. (View: 
    /var/www/mysite/resources/views/vendor/log-viewer/backpack/_master.blade.php) 
    (View: /var/www/mysite/resources/views/vendor/log- 
   viewer/backpack/_master.blade.php)"
`
![image](https://user-images.githubusercontent.com/3346239/73131794-5ef1a700-4009-11ea-9ad1-bdb93e3b8500.png)

**Comment by TheROPFather** [comment]
Is there any update on this?

@nomadtechiemike Did you find a solution?

**Comment by eduardoarandah** [comment]
Hello guys! I'm the package owner. 

Haven't had time to check the issue.

I think backpack V4 changed the base layout name to `layouts.top_left`

This could potentially be fixed by changing the first line in blade files to:

`@extends(backpack_view('layouts.top_left'))`

If you could test it and make the pull request it would be awesome!!

How to quickly do it:

- Fork this repo
- Go to your vendor folder and clone this repo instead of the one you find 
- Make changes
- Composer dump-autoload (maybe)

And then make the PR

Hope I can find the time to fix it myself

**Comment by eduardoarandah** [comment]
This issue is fixed. 

Republish view files with:
```
php artisan vendor:publish --provider="EduardoArandaH\BackpackLogViewer\BackpackLogViewerServiceProvider" --force
```

Also, you can add a better sidebar link version with:
```
php artisan backpack:add-sidebar-content "<li class='nav-item'><a class='nav-link' href='{{route(\"log-viewer::logs.list\")}}'><i class='nav-icon fa fa-history'></i> {{ trans('Logs') }}</a></li>"

```
